### ISSUE TITLE
Currently, what is the best gait recognition model based on the GREW dataset?

### ISSUE THREAD

**Issue by updatelse** [jdyjjj/All-in-One-Gait#5]
I would like to inquire with you about which gait recognition algorithm is currently the best based on the GREW dataset? I am researching related work on gait recognition. The best algorithm I have discovered myself seems to be the GaitBase model (which is open-source code).
I hope to receive your guidance.

**Comment by jdyjjj** [comment]
You can read this article Exploring Deep Models for Practical Gait Recognition on Google Academic.

**Comment by AhsanBilal7** [comment]
I am getting this error on running the Jupyter Notebook on my local machine
Cell In[1], line 6
      4 import sys
      5 sys.path.append(os.path.abspath('.') + "/demo/libs/")
----> 6 from track import *
      7 from segment import *
      8 from recognise import *

File [d:\fyp\all-in-one-gait\opengait\demo\libs\track.py:15](file:///D:/fyp/all-in-one-gait/opengait/demo/libs/track.py:15)
     13 from yolox.utils import fuse_model, get_model_info
     14 from loguru import logger
---> 15 from tracker.byte_tracker import BYTETracker
     16 from tracking_utils.timer import Timer
     17 from tracking_utils.visualize import plot_tracking, plot_track

File [d:\fyp\all-in-one-gait\opengait\demo\libs\tracker\byte_tracker.py:10](file:///D:/fyp/all-in-one-gait/opengait/demo/libs/tracker/byte_tracker.py:10)
      7 import torch.nn.functional as F
      9 from .kalman_filter import KalmanFilter
---> 10 from tracker import matching
     11 from .basetrack import BaseTrack, TrackState
     13 class STrack(BaseTrack):

File [d:\fyp\all-in-one-gait\opengait\demo\libs\tracker\matching.py:7](file:///D:/fyp/all-in-one-gait/opengait/demo/libs/tracker/matching.py:7)
      4 import lap
...

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:


I tried by downgrading the numpy version, but lower versions are not compatible with scipy and pandas
