### ISSUE TITLE
ImportError: generic_type

### ISSUE THREAD

**Issue by Mohades2023** [jdyjjj/All-in-One-Gait#8]
Hi, I have tried to run it in Python 3.8 but I have got this error, Could you help me with this.
My Gpu is nvidia geforce1070.
![error](https://github.com/jdyjjj/All-in-One-Gait/assets/139839556/3aae2b45-b58a-4c16-a64c-eb650aee99f0)

Thank you

**Comment by jdyjjj** [comment]
This problem seems to be a configuration issue with PaddlePaddle. You can consult with the PaddlePaddle project on how to solve this problem.
